; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino

; use the native USB CDC as a serial port + upload path
upload_protocol = esptool
; set your detected port (Windows example)
upload_port = COMx
monitor_port = COMx
monitor_speed = 250000

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DUSB_MANUFACTURER="TR"
  -DUSB_PRODUCT="ESP32-C6 ECG"
  -DCONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=10
  -DCONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=32
  -DBOARD_HAS_PSRAM=0

; WiFi library is included in ESP32 Arduino core by default